version: "3.1"

services:
  saft-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: saft-dev
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgres/data
    networks:
      - postgres-net

  saft-adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - postgres-net

networks:
  postgres-net:
    driver: bridge
