version: "3.1"

services:
  saft-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: saft-dev
    ports:
      - 5432:5432

  saft-adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
