name: Build and deploy SAFT

on:
  push:
    branches:
      - main
      - MD/feature/cd-pipeline
  pull_request:
    branches:
      - main

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build and push docker image
        working-directory: ./src/saft
        run: ./gradlew build "-Dquarkus.profile=cd"

      - name: Pull image and start container on remote
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            cd ~/saft-home/SSL-SAFT-Infrastructure/remote/saft-backend
            docker compose pull
            docker compose up -d
